#define TOKEN_QUESTION                        1
#define TOKEN_FUNCTION                        2
#define TOKEN_WHILE                           3
#define TOKEN_FOR                             4
#define TOKEN_REPEAT                          5
#define TOKEN_IF                              6
#define TOKEN_ELSE                            7
#define TOKEN_LEFT_ASSIGN                     8
#define TOKEN_EQ_ASSIGN                       9
#define TOKEN_RIGHT_ASSIGN                   10
#define TOKEN_TILDE                          11
#define TOKEN_OR                             12
#define TOKEN_OR2                            13
#define TOKEN_AND                            14
#define TOKEN_AND2                           15
#define TOKEN_NOT                            16
#define TOKEN_GT                             17
#define TOKEN_GE                             18
#define TOKEN_LT                             19
#define TOKEN_LE                             20
#define TOKEN_EQ                             21
#define TOKEN_NE                             22
#define TOKEN_PLUS                           23
#define TOKEN_MINUS                          24
#define TOKEN_TIMES                          25
#define TOKEN_DIVIDE                         26
#define TOKEN_SPECIALOP                      27
#define TOKEN_COLON                          28
#define TOKEN_UMINUS                         29
#define TOKEN_UPLUS                          30
#define TOKEN_POW                            31
#define TOKEN_DOLLAR                         32
#define TOKEN_AT                             33
#define TOKEN_NS_GET                         34
#define TOKEN_NS_GET_INT                     35
#define TOKEN_LPAREN                         36
#define TOKEN_LBRACKET                       37
#define TOKEN_LBB                            38
#define TOKEN_LBRACE                         39
#define TOKEN_NUM_CONST                      40
#define TOKEN_STR_CONST                      41
#define TOKEN_NULL_CONST                     42
#define TOKEN_SYMBOL                         43
#define TOKEN_RBRACE                         44
#define TOKEN_RPAREN                         45
#define TOKEN_IN                             46
#define TOKEN_RBB                            47
#define TOKEN_RBRACKET                       48
#define TOKEN_NEXT                           49
#define TOKEN_BREAK                          50
#define TOKEN_NEWLINE                        51
#define TOKEN_SEMICOLON                      52
#define TOKEN_COMMA                          53
